<form action="/users" method = "get">
    <input type="search" name = "includes">
    <input type="submit" value = "Search">
</form>
<ul>
<?php foreach($users as $user) :?>
<div style = "display:flex; width:200px; justify-content:space-between;list-style:none">
<li><h3><?= $user['name'] ?></h3></li>
<li><h3><?= $user['password'] ?></h3></li>
</div>
<?php endforeach?>
</ul>
<form action="/usersForm" method = "get">
    <input type="submit" value = "New user">
</form>