<h1>New User</h1>
<form action="/users" method="post">
    <label>
        Имя
    <input type="text" name = "user[name]">
    </label>
    <?php if (isset($errors['name'])): ?>
      <div><?= $errors['name'] ?></div>
    <?php endif ?>
    <label>
        Пароль
    <input type="password" name = "user[password]">
    </label>
    <?php if (isset($errors['password'])): ?>
      <div><?= $errors['password'] ?></div>
    <?php endif ?>
    <input type="submit" value="Отправить">
    
</form>